// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuA_um2SXaPXbEcpn3yvW_mvTdwUFnHXQ',
    appId: '1:954515661623:web:02604a58f4dca9fa2ef0b2',
    messagingSenderId: '954515661623',
    projectId: 'orderflow-r7jsk',
    authDomain: 'orderflow-r7jsk.firebaseapp.com',
    databaseURL: 'https://orderflow-r7jsk-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'orderflow-r7jsk.firebasestorage.app',
    measurementId: 'G-R079272FSE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUU71TYtfCIqTKwj1SHlbVhqqgbfEHx6U',
    appId: '1:954515661623:android:b798314ceba1b7352ef0b2',
    messagingSenderId: '954515661623',
    projectId: 'orderflow-r7jsk',
    databaseURL: 'https://orderflow-r7jsk-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'orderflow-r7jsk.firebasestorage.app',
  );

}